# Generated by Django 3.1.2 on 2020-10-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201026_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='register_date',
            field=models.DateField(auto_now=True),
        ),
    ]
